# Base image for Python
FROM python:3.10-slim

# Install required system packages
RUN apt-get update && apt-get install -y g++

# Set the working directory
WORKDIR /app

# Copy project files to the container
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir telebot pymongo aiohttp

# Compile the C++ file
RUN g++ -std=c++14 soul.cpp -o soul -pthread

# Command to run your Python script
CMD ["python3", "soul.py"]
