name: Deploy to AWS and Run Python Script

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the base runner

    steps:
    # Checkout the code from your GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telebot pymongo aiohttp

    # Set executable permissions on all files in the repository
    - name: Set permissions
      run: chmod +x *

    # Set up AWS credentials using GitHub secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Run the Python script (e.g., rohit.py)
    - name: Run Python script
      run: python3 rohit.py
